revista/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^revista/(?P<pk>[0-9]+)/$', views.revista_detail, name="revista-detail"),
    url(r'^lang/(?P<lang_code>\w+)/$', views.set_lang, name='set_lang'),
    url(r'^articulo/(?P<pk>[0-9]+)/$', views.DetailArticuloView.as_view(), name='articulo-detalle'),
    url(r'^busqueda-avanzada/$', views.busqueda, name="busqueda"),
    url(r'^busqueda/$', views.busqueda_avanzada, name="busqueda-avanzada"),
    #url(r'^busqueda/$', views.busqueda_google, name="googlesearch-results"),
    url(r'^archivos/$', views.archivos_revista, name="archivos"),
    url(r'^archivos/(?P<yearr>[0-9]+)/$', views.archivos_revista, name="archivos"),
    url(r'^subcribase/$', views.suscribete, name="suscribete"),
    url(r'^busqueda-por-tema/(?P<pk>[0-9]+)/$', views.articulo_busqueda_tema, name="tema"),
    url(r'^busqueda-por-zona/(?P<pk>\w+)/$', views.articulo_busqueda_zona, name="zona"),
    url(r'^busqueda-por-autor/(?P<pk>[0-9]+)/$', views.articulo_busqueda_autor, name="autor"),

]

revistaenvio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from revista.feeds import LatestRevistaFeed

urlpatterns = [
    url(r'^busqueda/', include('django_google_cse.urls')),
    url(r'', include('revista.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^rss/$', LatestRevistaFeed()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

revista/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from sorl.thumbnail import ImageField
from .utils import get_file_path

class Idiomas(models.Model):
    id = models.CharField(primary_key=True, max_length=2)
    idioma = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.idioma

    class Meta:
        db_table = 'idiomas'
        verbose_name='Idioma'
        verbose_name_plural='Idiomas'

class Zonas(models.Model):
    id = models.CharField(primary_key=True, max_length=2)
    zona = models.CharField(max_length=50, blank=True, null=True)
    relevancia = models.IntegerField(blank=True, null=True)
    zona_en = models.CharField(max_length=50, blank=True, null=True)
    zona_es = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.zona

    class Meta:
        db_table = 'zonas'
        verbose_name='Zona'
        verbose_name_plural='Zonas'
        ordering = ('zona',)

class Temas(models.Model):
    tema = models.CharField(max_length=150, blank=True, null=True)
    tema_en = models.CharField(max_length=150, blank=True, null=True)
    tema_es = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.tema

    class Meta:
        db_table = 'temas'
        verbose_name='Tema'
        verbose_name_plural='Temas'
        ordering = ('tema',)

class Autores(models.Model):
    nombre = models.CharField(_('Nombre'), max_length=150, blank=True, null=True)
    email = models.CharField(_('Correo'), max_length=50, blank=True, null=True)
    titulo = models.CharField(_('Titulo'), max_length=50, blank=True, null=True)
    cargo = models.TextField(_('Cargo'), blank=True, null=True)
    nota = models.TextField(_('Nota'), blank=True, null=True)
    nombre_en = models.CharField(_('Nombre ingles'), max_length=150, blank=True, null=True)
    nombre_es = models.CharField(_('Nombre en español'), max_length=150, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.nombre

    class Meta:
        db_table = 'autores'
        verbose_name= _('Autor')
        verbose_name_plural= _('Autores')
        ordering = ('nombre',)

CHOICES_MES = (
        (1, _('Enero')),
        (2, _('Febrero')),
        (3, _('Marzo')),
        (4, _('Abril')),
        (5, _('Mayo')),
        (6, _('Junio')),
        (7, _('Julio')),
        (8, _('Agosto')),
        (9, _('Septiembre')),
        (10, _('Octubre')),
        (11, _('Noviembre')),
        (12, _('Diciembre'))
    )

class ColoresRevista(models.Model):
    color1 = models.CharField(max_length=50, null=True, blank=True)
    color2 = models.CharField(max_length=50, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.color1

class Revistas(models.Model):
    volumen = models.IntegerField()
    ano = models.IntegerField('Año', blank=True, null=True)
    mes = models.IntegerField(choices=CHOICES_MES, blank=True, null=True)
    numero = models.IntegerField(blank=True, null=True)
    ididioma = models.ForeignKey(Idiomas, verbose_name='idioma')
    nota = models.TextField(blank=True, null=True)
    color = models.ForeignKey(ColoresRevista, blank=True, null=True)
    portada = ImageField(upload_to=get_file_path, null=True, blank=True)

    fileDir = 'portadas/'

    def __str__(self):
        return u'%s %s: Número: %s - Idioma: %s' % (str(self.get_mes_display()),str(self.ano),str(self.numero),self.ididioma)

    class Meta:
        db_table = 'revistas'
        verbose_name='Revista'
        verbose_name_plural='Revistas'
        ordering = ('-numero','-mes')

CHOICE_OPINION = ( (1, 'Opinion'),
                   (2, 'Speaking-Out'),
                   (3, 'Analysis'),
                   (4, 'The Month'),
                   (5, 'Close-Up'),
                   (6, 'Eulogy')
                  )

class Articulos(models.Model):
    revista = models.ForeignKey(Revistas)
    titulo = models.CharField(max_length=255, blank=True, null=True)
    opinion = models.IntegerField(choices=CHOICE_OPINION, null=True, blank=True,
                                  verbose_name='Categorías en inglés')
    idioma = models.ForeignKey(Idiomas, null=True, blank=True)
    idzona = models.ForeignKey('Zonas', blank=True, null=True, verbose_name='Zona')
    autor = models.ForeignKey('Autores', blank=True, null=True, verbose_name='Autor')
    autornota = RichTextField('Introducción', blank=True, null=True)
    cambio = RichTextField(blank=True, null=True)
    texto = RichTextUploadingField(blank=True, null=True)
    codigoml = models.IntegerField(blank=True, null=True)
    nota = RichTextField(blank=True, null=True)
    temas = models.ManyToManyField(Temas, blank=True)

    def __str__(self):
        return self.titulo

    class Meta:
        db_table = 'articulos'
        verbose_name='Articulo'
        verbose_name_plural='Articulos'
        ordering = ['id']
        #ordering = ['-revista__ano','-revista__mes']


# class Articulotemas(models.Model):
#     idarticulo = models.ForeignKey(Articulos, models.DO_NOTHING, db_column='idarticulo')
#     idtema = models.ForeignKey('Temas', models.DO_NOTHING, db_column='idtema')
#     ididioma = models.CharField(max_length=2, blank=True, null=True)

#     class Meta:
#         #managed = False
#         db_table = 'articulotemas'
#         unique_together = (('idarticulo', 'idtema'),)

class Enlaces(models.Model):
    titulo = models.TextField(blank=True, null=True)
    texto = models.TextField(blank=True, null=True)
    idarticulo = models.ForeignKey(Articulos, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.titulo

    class Meta:
        db_table = 'enlaces'
        verbose_name='Enlace'
        verbose_name_plural='Enlaces'

class Tipo(models.Model):
    id = models.CharField(primary_key=True, max_length=3)
    tipo = models.CharField(max_length=500, blank=True, null=True)
    precio = models.CharField(max_length=50, blank=True, null=True)
    tipo_es = models.CharField(max_length=500, blank=True, null=True)
    tipo_en = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return u'%s - %s' % (self.tipo, self.precio)

    class Meta:
        db_table = 'tipo'
        verbose_name='Tipo'
        verbose_name_plural='Tipos'


class Envio(models.Model):
    envio = models.CharField(max_length=500, blank=True, null=True)
    institucion = models.CharField(max_length=500, blank=True, null=True)
    direccion = models.CharField(max_length=500, blank=True, null=True)
    email = models.CharField(max_length=500, blank=True, null=True)
    apdo = models.CharField(max_length=50, blank=True, null=True)
    telefono = models.CharField(max_length=50, blank=True, null=True)
    fax = models.CharField(max_length=50, blank=True, null=True)
    ciudad = models.CharField(max_length=100, blank=True, null=True)
    codigo = models.CharField(max_length=50, blank=True, null=True)
    idpais = models.CharField(max_length=2, blank=True, null=True)
    nueva = models.NullBooleanField()
    idioma = models.CharField(max_length=10, blank=True, null=True)
    forma_pago = models.CharField(max_length=2, blank=True, null=True)
    ttipo = models.CharField(max_length=4, blank=True, null=True)
    tnumero = models.CharField(max_length=50, blank=True, null=True)
    texpira = models.CharField(max_length=10, blank=True, null=True)
    tnombre = models.CharField(max_length=200, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    nombre = models.CharField(max_length=500, blank=True, null=True)
    idtipo = models.ForeignKey('Tipo', models.DO_NOTHING, db_column='idtipo', blank=True, null=True)
    suscripcion = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.institucion

    class Meta:
        db_table = 'envio'
        verbose_name='Registro de subcriptores'
        verbose_name_plural='Registros de subcriptores'


class Pais(models.Model):
    id = models.CharField(primary_key=True, max_length=2)
    pais = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.pais

    class Meta:
        db_table = 'pais'
        verbose_name='Pais'
        verbose_name_plural='Paises'
        ordering = ('pais',)

revista/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm, Textarea
from ckeditor.widgets import CKEditorWidget
from .models import Articulos, Envio, Temas, Zonas, CHOICES_MES, Revistas
from django.utils import translation

class ArticulosAdminForm(ModelForm):
    class Meta:
        model = Articulos
        fields = '__all__'

class SubcribeteForm(ModelForm):
    class Meta:
        model = Envio
        fields = '__all__'


def choice_year():
    cur_language = translation.get_language()
    all_year1 = []
    if cur_language == 'en':
        years = []
        for en in Revistas.objects.filter(ididioma='en').order_by('-ano').values_list('ano', flat=True):
            years.append((en,en))
        all_year1 = list(sorted(set(years)))
    else:
        years = []
        for en in Revistas.objects.filter(ididioma='es').order_by('-ano').values_list('ano', flat=True):
            years.append((en,en))
        all_year1 = list(sorted(set(years)))
    return all_year1

class BusquedaAvanzada(forms.Form):
    #------- inicio --------------
    mes_1 = forms.ChoiceField(choices=CHOICES_MES)
    year_1 = forms.ChoiceField(choices=choice_year())
    #-------- fin ----------------
    mes_2 = forms.ChoiceField(choices=CHOICES_MES)
    year_2 = forms.ChoiceField(choices=choice_year())
    #------- zona ---------------
    zona = forms.ModelMultipleChoiceField(queryset=Zonas.objects.all(), required=False)
    temas = forms.ModelMultipleChoiceField(queryset=Temas.objects.all(), required=False)
    #----- input busqueda ---------
    buscar = forms.CharField(max_length=250)

templates/revista/archivos.html
{% extends "base.html" %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block contenido %}
<style type="text/css">
    .articulo-titulo{
        color:  #a90129;
        border-bottom: 1px solid    #fbf2f4;
    }
    .articulo-titulo .item ul{
        list-style: none;
        padding: 0px
    }
    .lista-articulos li a:hover{
        color:  #a90129;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <div class="container-archivo">
                <div class="select-archivo">
                <ul>
                    <li class="dw"><h6> <span class="fa fa-file-o"> </span>{% trans "Archivo año"%}</h6></li>
                    <li class="dw">
                        <div class="dropdown">
                            <button class="dropdown-toggle dw-anos" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                {{query.0.ano}}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                {% for obj in all_year1 reversed %}
                                <li><a href="{% url 'archivos' obj.0 %}">{{obj.0}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
                    
                    
                </div>
                
            </div>
            <div class="articulos">

                <div class="item">

                    {% for valor in query %}
                    <h5 class="articulo-titulo"> {{valor.ano}} {{valor.get_mes_display}}  No.{{valor.numero}}</h5>

                    <ul class="lista-articulos">
                        {% for obj in valor.articulos_set.all %}
                        <li><a href="{% url 'articulo-detalle' obj.id %}"><strong>
                            {% if LANGUAGE_CODE == 'es' %}
                                {{obj.idzona}}
                            {% else %}
                                {{obj.idzona.zona_en}}
                            {% endif %}
                        :</strong> {{obj}}</a></li>
                        {% endfor %}
                    </ul>
                    {% endfor %}

                </div>
            </div>
        </div>
        {% include "sidebar.html" %}
        
        
    </div>
</div>
{% endblock contenido %}

templates/revista/busqueda_mega_avanzada.html
{% extends "base.html" %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% block extra_js %}
<script type="text/javascript">
 var urlmenu = document.getElementById( 'archivosDrop' );
 urlmenu.onchange = function() {
      window.open( this.options[ this.selectedIndex ].value, '_self');
 };
</script>
{% endblock extra_js %}
{% block contenido %}
<style type="text/css">
        .barra-superior, .main-manu, .navbar-brand, .idiomas a.activo, .suscripcion a,
        footer,.navbar-toggle .icon-bar{

            background-color: #a90129;
        }
        .idiomas a.activo{
            color: white;
            border-color: #a90129;
        }
        .navbar-toggle{
            border-color: #a90129;
        }
        .revista-actual span, .pais,.pais span,
        .articulos p span a, .articulo-detalle h1, .articulo-detalle h2, .articulo-detalle h3,
        .articulo-detalle h4, .articulo-detalle h5, .articulo-detalle h6, a.link-titulo:hover,
        a.link-titulo:focus{
            color:#a90129;
        }
        hr{
            border-color:   #fbf2f4;

        }
        .revista-actual, .navbar-envios{
            border-bottom: 1px solid    #fbf2f4;
        }
        .sidebar, .sm-menu{
            background-color:   #fbf2f4;
        }

    </style>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <div class="revista-actual">
                
                <span class="fa fa-search"> {% trans "Búsqueda avanzada:" %}              
                busqueda general: 
                </span>
            </div>
            <div class="articulos">
                {% for obj in object_list %}
                    <div class="item">
                        <h6 class="pais">{{obj.idzona}}
                                <span>

                                    {% if LANGUAGE_CODE == 'es' %}
                                        
                                    {% else %}
                                        {% if obj.opinion %}
                                            - {{obj.get_opinion_display}}
                                        {% endif %}
                                       
                                    {% endif %}
                                </span>
                        </h6>
                        <h5 class="articulo-titulo"><a href="{% url 'articulo-detalle' obj.id %}">{{obj}}</a></h5>
                        <p>
                            {{obj.texto|truncatewords:22|striptags|safe }}
                            <span><a href="{% url 'articulo-detalle' obj.id %}"><span class="fa fa-arrow-right"></span></a></span>
                        </p>
                    </div>
                    <hr>
                {% endfor %}

        <div class="paginado">
            <span class="step-links">
                {% if object_list.has_previous %}
                    <a href="?page={{ object_list.previous_page_number }}">{% trans "Anterior" %}</a>
                {% endif %}

                <span class="current">
                    {% trans "Pagina" %} {{ object_list.number }} {% trans "de" %} {{ object_list.paginator.num_pages }}.
                </span>

                {% if object_list.has_next %}
                    <a href="?page={{ object_list.next_page_number }}">{% trans "Siguientes" %}</a>
                {% endif %}
            </span>
        </div>

            </div>
        </div>
        {% include "sidebar.html" %}
    </div>
</div>
{% endblock contenido %}

templates/revista/suscribete.html
{% extends "base.html" %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block extra_js %}
<script type="text/javascript">
 var urlmenu = document.getElementById( 'archivosDrop' );
 urlmenu.onchange = function() {
      window.open( this.options[ this.selectedIndex ].value, '_self');
 };
$( '#id_idtipo, #id_nombre, #id_institucion,#id_direccion,#id_email,#id_idpais,#id_ciudad,#id_codigo, #id_apdo, #id_fax, #id_nueva,#id_idioma,#id_telefono,#id_envio,#id_ttipo,#id_tnumero,#id_fecha,#id_tnombre' ).addClass( "form-control" );
</script>
{% endblock extra_js %}

{% block contenido %}
 <style type="text/css">
        .barra-superior, .main-manu, .navbar-brand, .idiomas a.activo, .suscripcion a,
        footer,.navbar-toggle .icon-bar, .btn-sub{

            background-color: #a90129;
        }
        .idiomas a.activo{
            color: white;
            border-color: #a90129;
        }
        .navbar-toggle{
            border-color: #a90129;
        }
        .revista-actual span, .pais,.pais span,
        .articulos p span a, .articulo-detalle h1, .articulo-detalle h2, .articulo-detalle h3,
        .articulo-detalle h4, .articulo-detalle h5, .articulo-detalle h6, a.link-titulo:hover,
        a.link-titulo:focus, .sub-titulo{
            color:#a90129;
        }
        hr{
            border-color:   #fbf2f4;

        }
        .revista-actual, .navbar-envios{
            border-bottom: 1px solid    #fbf2f4;
        }
        .sidebar, .sm-menu{
            background-color:   #fbf2f4;
        }

    </style>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <div class="revista-actual">
                <div class="sub-titulo">{% trans "Suscribete" %}</div>
            </div>

            <div class="articulos">
                {{ form.non_field_errors }}
                <form action="http://www.google.com" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.idtipo.id_for_label }}"> {% trans "Suscripción anual de 11 números" %} </label>
                                {{ form.idtipo }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.nombre.id_for_label }}"> {% trans "Nombres y apellidos" %} </label>
                                {{ form.nombre }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.idpais.id_for_label }}"> {% trans "Pais" %} </label>
                                {{ form.idpais }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.ciudad.id_for_label }}"> {% trans "Ciudad" %} </label>
                                {{ form.ciudad }}
                            </div>
                        </div>
                                
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="form-group">
                                <label for="{{ form.direccion.id_for_label }}"> {% trans "Dirección" %} </label>
                                {{ form.direccion }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.institucion.id_for_label }}"> {% trans "Institución" %} </label>
                                {{ form.institucion }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.email.id_for_label }}"> {% trans "Correo electrónico" %} </label>
                                {{ form.email }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.codigo.id_for_label }}"> {% trans "Código postal" %} </label>
                                {{ form.codigo }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.apdo.id_for_label }}"> {% trans "Apartado postal" %} </label>
                                {{ form.apdo }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.telefono.id_for_label }}"> {% trans "Teléfono" %} </label>
                                {{ form.telefono }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.fax.id_for_label }}"> {% trans "Fax" %} </label>
                                {{ form.fax }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.nueva.id_for_label }}"> {% trans "Suscripción" %} </label>
                                {{ form.nueva }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.idioma.id_for_label }}"> {% trans "Idioma" %} </label>
                                {{ form.idioma }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <div class="form-group">
                                <label for="{{ form.envio.id_for_label }}"> {% trans "Envio" %} </label>
                                {{ form.envio }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.ttipo.id_for_label }}"> {% trans "Datos tarjeta de crédito" %} </label>
                                {{ form.ttipo }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.tnumero.id_for_label }}"> {% trans "Número de tarjeta" %} </label>
                                {{ form.tnumero }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.fecha.id_for_label }}"> {% trans "Fecha de vencimiento" %} </label>
                                {{ form.fecha }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="{{ form.tnombre.id_for_label }}"> {% trans "Nombre del tarjeta habiente" %} </label>
                                {{ form.tnombre }}
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                            <p>
                                Por la presente autorizo al Instituto Histórico Centroamericano (IHCA) a cargar los gastos de mi suscripción a la revista Envío a mi tarjeta de crédito actual, como se indica en esta solicitud.
                                Si desea cancelar en EFECTIVO, CHEQUE o DEPOSITO (o prefiere enviar los datos por fax o correo) llene el siguiente formulario. Estos datos deben ser enviados a: Revista Envío, Apartado Postal A-194, Managua, Nicaragua. 
                            </p>

                            <div class="checkbox">
                                <input id="checkbox1" type="checkbox">
                                <label for="checkbox1">
                                    Estoy de acuerdo
                                </label>
                            </div>
                            <hr>
                            <div class="">
                                <h5>Para suscripciones electrónicas: </h5>
                                <p>
                                   Los campos con asteriscos (*) son requeridos. Su correo electrónico será utilizado como medio para enviarle la revista mensualmente. 
                                </p>
                                <p>
                                   Los archivos serán enviados en formatos PDF. 
                                </p>
                                <p>
                                  Los textos de la revista Envío tienen “derechos compartidos”. Pueden ser reproducidos libremente. Solamente agradeceremos nos lo comuniquen a nuestra dirección electrónica.
                                </p>
                            </div>
                            <hr>
                            <input type="submit" class="btn btn-sub center-block" value="Enviar" />
                        </div>

                    </div>
                </form>
            </div>
        </div>
        {% include "sidebar.html" %}
    </div>
</div>
{% endblock contenido %}