revista/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name="index"),
    url(r'^revista/(?P<pk>[0-9]+)/$', views.revista_detail, name="revista-detail"),
    url(r'^lang/(?P<lang_code>\w+)/$', views.set_lang, name='set_lang'),
    url(r'^articulo/(?P<pk>[0-9]+)/$', views.DetailArticuloView.as_view(), name='articulo-detalle'),
    url(r'^busqueda-avanzada/$', views.busqueda, name="busqueda"),
    url(r'^busqueda/$', views.busqueda_avanzada, name="busqueda-avanzada"),
    #url(r'^busqueda/$', views.busqueda_google, name="googlesearch-results"),
    url(r'^archivos/$', views.archivos_revista, name="archivos"),
    url(r'^archivos/(?P<yearr>[0-9]+)/$', views.archivos_revista, name="archivos"),
    url(r'^subcribase/$', views.suscribete, name="suscribete"),
    url(r'^busqueda-por-tema/(?P<pk>[0-9]+)/$', views.articulo_busqueda_tema, name="tema"),
    url(r'^busqueda-por-zona/(?P<pk>\w+)/$', views.articulo_busqueda_zona, name="zona"),
    url(r'^busqueda-por-autor/(?P<pk>[0-9]+)/$', views.articulo_busqueda_autor, name="autor"),

]

revistaenvio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from revista.feeds import LatestRevistaFeed

urlpatterns = [
    url(r'^busqueda/', include('django_google_cse.urls')),
    url(r'', include('revista.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'^rss/$', LatestRevistaFeed()),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

fotosportada/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from sorl.thumbnail import ImageField
from revista.utils import get_file_path

# Create your models here.

class FotosPortada(models.Model):
	titulo = models.CharField(max_length=250)

	def __str__(self):
		return self.titulo

	class Meta:
		verbose_name = 'Fotos portada'
		verbose_name_plural = 'Fotos de las Portadas'

class Fotos(models.Model):
	portada = models.ForeignKey(FotosPortada)
	imagen = ImageField(upload_to=get_file_path, null=True, blank=True)
	frase = models.TextField()
	frase_en = models.TextField(null=True, blank=True)
	autor = models.CharField(max_length=250)
	autor_en = models.CharField(max_length=250, null=True, blank=True)

	fileDir = 'slider/'

	def __str__(self):
		return self.portada.titulo

	class Meta:
		verbose_name = 'Foto'
		verbose_name_plural = 'Fotos'
		ordering = ('id',)

revista/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext_lazy as _
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from sorl.thumbnail import ImageField
from .utils import get_file_path

class Idiomas(models.Model):
    id = models.CharField(primary_key=True, max_length=2)
    idioma = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.idioma

    class Meta:
        db_table = 'idiomas'
        verbose_name='Idioma'
        verbose_name_plural='Idiomas'

class Zonas(models.Model):
    id = models.CharField(primary_key=True, max_length=2)
    zona = models.CharField(max_length=50, blank=True, null=True)
    relevancia = models.IntegerField(blank=True, null=True)
    zona_en = models.CharField(max_length=50, blank=True, null=True)
    zona_es = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.zona

    class Meta:
        db_table = 'zonas'
        verbose_name='Zona'
        verbose_name_plural='Zonas'
        ordering = ('zona',)

class Temas(models.Model):
    tema = models.CharField(max_length=150, blank=True, null=True)
    tema_en = models.CharField(max_length=150, blank=True, null=True)
    tema_es = models.CharField(max_length=150, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.tema

    class Meta:
        db_table = 'temas'
        verbose_name='Tema'
        verbose_name_plural='Temas'
        ordering = ('tema',)

class Autores(models.Model):
    nombre = models.CharField(_('Nombre'), max_length=150, blank=True, null=True)
    email = models.CharField(_('Correo'), max_length=50, blank=True, null=True)
    titulo = models.CharField(_('Titulo'), max_length=50, blank=True, null=True)
    cargo = models.TextField(_('Cargo'), blank=True, null=True)
    nota = models.TextField(_('Nota'), blank=True, null=True)
    nombre_en = models.CharField(_('Nombre ingles'), max_length=150, blank=True, null=True)
    nombre_es = models.CharField(_('Nombre en español'), max_length=150, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.nombre

    class Meta:
        db_table = 'autores'
        verbose_name= _('Autor')
        verbose_name_plural= _('Autores')
        ordering = ('nombre',)

CHOICES_MES = (
        (1, _('Enero')),
        (2, _('Febrero')),
        (3, _('Marzo')),
        (4, _('Abril')),
        (5, _('Mayo')),
        (6, _('Junio')),
        (7, _('Julio')),
        (8, _('Agosto')),
        (9, _('Septiembre')),
        (10, _('Octubre')),
        (11, _('Noviembre')),
        (12, _('Diciembre'))
    )

class ColoresRevista(models.Model):
    color1 = models.CharField(max_length=50, null=True, blank=True)
    color2 = models.CharField(max_length=50, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.color1

class Revistas(models.Model):
    volumen = models.IntegerField()
    ano = models.IntegerField('Año', blank=True, null=True)
    mes = models.IntegerField(choices=CHOICES_MES, blank=True, null=True)
    numero = models.IntegerField(blank=True, null=True)
    ididioma = models.ForeignKey(Idiomas, verbose_name='idioma')
    nota = models.TextField(blank=True, null=True)
    color = models.ForeignKey(ColoresRevista, blank=True, null=True)
    portada = ImageField(upload_to=get_file_path, null=True, blank=True)

    fileDir = 'portadas/'

    def __str__(self):
        return u'%s %s: Número: %s - Idioma: %s' % (str(self.get_mes_display()),str(self.ano),str(self.numero),self.ididioma)

    class Meta:
        db_table = 'revistas'
        verbose_name='Revista'
        verbose_name_plural='Revistas'
        ordering = ('-numero','-mes')

CHOICE_OPINION = ( (1, 'Opinion'),
                   (2, 'Speaking-Out'),
                   (3, 'Analysis'),
                   (4, 'The Month'),
                   (5, 'Close-Up'),
                   (6, 'Eulogy')
                  )

class Articulos(models.Model):
    revista = models.ForeignKey(Revistas)
    titulo = models.CharField(max_length=255, blank=True, null=True)
    opinion = models.IntegerField(choices=CHOICE_OPINION, null=True, blank=True,
                                  verbose_name='Categorías en inglés')
    idioma = models.ForeignKey(Idiomas, null=True, blank=True)
    idzona = models.ForeignKey('Zonas', blank=True, null=True, verbose_name='Zona')
    autor = models.ForeignKey('Autores', blank=True, null=True, verbose_name='Autor')
    autornota = RichTextField('Introducción', blank=True, null=True)
    cambio = RichTextField(blank=True, null=True)
    texto = RichTextUploadingField(blank=True, null=True)
    codigoml = models.IntegerField(blank=True, null=True)
    nota = RichTextField(blank=True, null=True)
    temas = models.ManyToManyField(Temas, blank=True)

    def __str__(self):
        return self.titulo

    class Meta:
        db_table = 'articulos'
        verbose_name='Articulo'
        verbose_name_plural='Articulos'
        ordering = ['id']
        #ordering = ['-revista__ano','-revista__mes']


# class Articulotemas(models.Model):
#     idarticulo = models.ForeignKey(Articulos, models.DO_NOTHING, db_column='idarticulo')
#     idtema = models.ForeignKey('Temas', models.DO_NOTHING, db_column='idtema')
#     ididioma = models.CharField(max_length=2, blank=True, null=True)

#     class Meta:
#         #managed = False
#         db_table = 'articulotemas'
#         unique_together = (('idarticulo', 'idtema'),)

class Enlaces(models.Model):
    titulo = models.TextField(blank=True, null=True)
    texto = models.TextField(blank=True, null=True)
    idarticulo = models.ForeignKey(Articulos, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.titulo

    class Meta:
        db_table = 'enlaces'
        verbose_name='Enlace'
        verbose_name_plural='Enlaces'

class Tipo(models.Model):
    id = models.CharField(primary_key=True, max_length=3)
    tipo = models.CharField(max_length=500, blank=True, null=True)
    precio = models.CharField(max_length=50, blank=True, null=True)
    tipo_es = models.CharField(max_length=500, blank=True, null=True)
    tipo_en = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return u'%s - %s' % (self.tipo, self.precio)

    class Meta:
        db_table = 'tipo'
        verbose_name='Tipo'
        verbose_name_plural='Tipos'


class Envio(models.Model):
    envio = models.CharField(max_length=500, blank=True, null=True)
    institucion = models.CharField(max_length=500, blank=True, null=True)
    direccion = models.CharField(max_length=500, blank=True, null=True)
    email = models.CharField(max_length=500, blank=True, null=True)
    apdo = models.CharField(max_length=50, blank=True, null=True)
    telefono = models.CharField(max_length=50, blank=True, null=True)
    fax = models.CharField(max_length=50, blank=True, null=True)
    ciudad = models.CharField(max_length=100, blank=True, null=True)
    codigo = models.CharField(max_length=50, blank=True, null=True)
    idpais = models.CharField(max_length=2, blank=True, null=True)
    nueva = models.NullBooleanField()
    idioma = models.CharField(max_length=10, blank=True, null=True)
    forma_pago = models.CharField(max_length=2, blank=True, null=True)
    ttipo = models.CharField(max_length=4, blank=True, null=True)
    tnumero = models.CharField(max_length=50, blank=True, null=True)
    texpira = models.CharField(max_length=10, blank=True, null=True)
    tnombre = models.CharField(max_length=200, blank=True, null=True)
    fecha = models.DateTimeField(blank=True, null=True)
    nombre = models.CharField(max_length=500, blank=True, null=True)
    idtipo = models.ForeignKey('Tipo', models.DO_NOTHING, db_column='idtipo', blank=True, null=True)
    suscripcion = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.institucion

    class Meta:
        db_table = 'envio'
        verbose_name='Registro de subcriptores'
        verbose_name_plural='Registros de subcriptores'


class Pais(models.Model):
    id = models.CharField(primary_key=True, max_length=2)
    pais = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return u'%s' % self.pais

    class Meta:
        db_table = 'pais'
        verbose_name='Pais'
        verbose_name_plural='Paises'
        ordering = ('pais',)

templates/archivos.html
{% extends "base.html" %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block contenido %}
<style type="text/css">
    .articulo-titulo{
        color:  #a90129;
        border-bottom: 1px solid #fbf2f4;
    }
    .articulo-titulo .item ul{
        list-style: none;
        padding: 0px
    }
    .lista-articulos li a:hover{
        color:  #a90129;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <div class="container-archivo">
                <div class="select-archivo">
                <ul>
                    <li class="dw"><h6> <span class="fa fa-file-o"> </span>Archivo añ</h6></li>
                    <li class="dw">
                        <div class="dropdown">
                            <button class="dropdown-toggle dw-anos" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                {{query.0.ano}}
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                {% for obj in all_year reversed %}
                                <li><a href="{% url 'archivos' obj.0 %}">{{obj.0}}</a></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </li>
                </ul>
                    
                    
                </div>
                
            </div>
            <div class="articulos">
                   
            <div class="item">
                        
             {% for valor in query %}
             <h5 class="articulo-titulo">{{valor.get_mes_display}} No. {{valor}}</h5>
            
                <ol class="lista-articulos">
                    {% for obj in valor.articulos_set.all %}
                        <li><a href="{% url 'articulo-detalle' obj.id %}">{{obj.idzona}}: {{obj}}</a></li>
                    {% endfor %}
                </ol>
            {% endfor %}
                        
                    </div>
            </div>
        </div>
        {% include "sidebar.html" %}
    </div>
</div>
{% endblock contenido %}

templates/base.html
{% load google_cse_tags %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Revista Envío</title>
        <link rel="shortcut icon" href="/static/img/enviopeque.jpg">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" >
        <link rel="stylesheet" href="/static/font-awesome/css/font-awesome.min.css" >
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,400,700" rel="stylesheet">
        <link rel="stylesheet" href="/static/css/main.css" >
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.min.css" rel="stylesheet" />
        {% block share_fb %}{% endblock share_fb %}



    </head>
    <body>

 <style type="text/css">
        .barra-superior, .main-manu, .navbar-brand, .idiomas a.activo, .suscripcion a,
        footer,.navbar-toggle .icon-bar{

            background-color: #a90129;
        }
        .idiomas a.activo{
            color: white;
            border-color: #a90129;
        }
        .navbar-toggle, .container-archivo .select-archivo .dw-anos{
            border-color: #a90129;
        }
        .revista-actual span, .pais,.pais span,
        .articulos p span a, .articulo-detalle h1, .articulo-detalle h2, .articulo-detalle h3,
        .articulo-detalle h4, .articulo-detalle h5, .articulo-detalle h6, a.link-titulo:hover,
        a.link-titulo:focus, .sub-titulo{
            color:#a90129;
        }
        hr{
            border-color:   #fbf2f4;

        }

        .sidebar, .sm-menu{
            background-color:   #fbf2f4;
        }
        .select-archivo h6, .select-archivo .dw-anos{
            color:#a90129;
        }
        .container-archivo{
            border-color: #fbf2f4;
        }


    </style>
        <header>
            <!-- <div class="barra-superior">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-4 col-sm-8 col-md-9 col-lg-10">
                            <img class="logo2" src="/static/img/Icono de Envio.png" alt="">
                        </div>
                        <div class="col-xs-8 col-sm-4 col-md-3 col-lg-2">
                            <ul class="social-icon">
                                <li><a class="fa fa-facebook" href="https://www.facebook.com/Revista-Env%C3%ADo-105930609457482/" target="_blank"></a></li>
                                <li><a class="fa fa-twitter" href="https://twitter.com/RevistaEnvio" target="_blank"></a></li>
                                <li><a class="fa fa-google-plus" href="https://plus.google.com/u/1/+RevistaEnv%C3%ADoUCA" target="_blank"></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

            </div> -->
            <div class="main-manu">
                <nav class="navbar navbar-envios">
                    <div class="container">

                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="/"><img src="/static/img/logoblanco.png" alt=""></a>
                        </div>


                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        {% if LANGUAGE_CODE == 'es' %}
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active"><a href="/">{% trans "Inicio" %}</a></li>
                                <li><a href="/quienes-somos/">{% trans "¿Quiénes somos?" %}</a></li>
                                <li><a href="/busqueda-avanzada/">{% trans "Búsqueda" %}</a></li>
                                <li><a href="/archivos/">{% trans "Archivo" %}</a></li>
                                <li><a href="/equipo/">{% trans "Equipo"%}</a></li>
                            </ul>
                        {% else %}
                             <ul class="nav navbar-nav navbar-right">
                                <li class="active"><a href="/">{% trans "Inicio" %}</a></li>
                                <li><a href="/about-us/">{% trans "¿Quiénes Somos?" %}</a></li>
                                <li><a href="/busqueda-avanzada/">{% trans "Búsqueda" %}</a></li>
                                <li><a href="/archivos/">{% trans "Archivo" %}</a></li>
                                <li><a href="/team/">{% trans "Equipo"%}</a></li>
                            </ul>
                        {%endif%}
                        </div>
                    </div>
                </nav>
            </div>
            {% for obj in portada %}
            <div id="carousel-example" class="carousel slide" data-ride="carousel">
                <!-- <ol class="carousel-indicators">
                    {% for x in obj.fotos_set.all %}
                        <li data-target="#carousel-example" data-slide-to="{{forloop.revcounter0}}" {% if forloop.counter == 1 %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>-->

              <div class="carousel-inner">
                {% for x in obj.fotos_set.all %}
                <div class="item {% if forloop.counter == 1 %}active{% endif %}">
                    {% thumbnail x.imagen "x400" crop="center" as im %}
                    <a href="#"><img src="{{ im.url }}" height="{{ im.height }}"/></a>
                    {% endthumbnail %}

                  <div class="carousel-caption">
                  {% if LANGUAGE_CODE == 'es' %}
                    <p>{{x.frase|safe}}</p>
                    <p class="autor-slide">- {{x.autor}}</p>
                  {% else %}
                    <p>{{x.frase_en|safe}}</p>
                    <p class="autor-slide">- {{x.autor_en}}</p>
                  {% endif %}

                  </div>
                </div>
                {% endfor %}

              </div>

              <a class="left carousel-control" href="#carousel-example" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
              </a>
              <a class="right carousel-control" href="#carousel-example" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
              </a>
            </div>
             {% endfor %}

        </header>

        <div class="contenido">
            <div class="sm-menu visible-xs">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="idioma-container">
                            <h6>{% trans "Idioma" %}</h6>
                            <div class="idiomas container-fluid">
                                <div class="row">
                                    <a href="/lang/es/" class="col-xs-6 col-sm-6 col-md-6 col-lg-6 es {% if LANGUAGE_CODE == 'es' %}activo{% endif %} ">
                                        {% trans "Español"%}
                                    </a>
                                    <a href="/lang/en/" class="col-xs-6 col-sm-6 col-md-6 col-lg-6 en {% if LANGUAGE_CODE == 'en' %}activo{% endif %}">
                                        {% trans "Ingles"%}
                                    </a>
                                    <a href="http://www.ans21.org" class="col-xs-6 col-sm-6 col-md-6 col-lg-4 it target="_blank"">
                                        {% trans "Italiano"%}
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
            {% block contenido %}

            {% endblock contenido %}
        </div>
        <footer>
            <div class="logo-footer">
                <img class="center-block" src="/static/img/logoblanco.png" alt="">
            </div>
            <div class="sub-footer">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                            <div class="texto-left">
                                <p>Revista Envío
                                <br> Edificio Nitlapán, 2do. piso
                                <br>Universidad Centroamericana UCA
                                </p>
                                <p>
                                    Apartado A-194
                                    <br>Managua, Nicaragua
                                </p>

                            </div>

                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                            <div class="texto-central">
                                <p>Tel: (505) 22782557</p>
                                <p>Email: envio@envio.org.ni</p>
                                <ul class="social-icon footer-social">
                                    <li><a class="fa fa-facebook" href="https://www.facebook.com/Revista-Env%C3%ADo-105930609457482/" target="_blank"></a></li>
                                    <li><a class="fa fa-twitter" href="https://twitter.com/RevistaEnvio" target="_blank"></a></li>
                                    <li><a class="fa fa-google-plus" href="https://plus.google.com/u/1/+RevistaEnv%C3%ADoUCA" target="_blank"></a></li>
                                </ul>
                                <p>
                                   Revista envío digital
                                <br>
                                    {% trans "Desarrollado por " %}<a href="http://simas.org.ni">SIMAS</a>
                                </p>
                            </div>

                        </div>
                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
                            <div class="texto-right">
                                <p>
                                    {% blocktrans %}Revista mensual de ánalisis <br>
                                    de Nicaragua y Centroamérica
                                    {% endblocktrans %}
                                </p>
                                <ul class="logos-footer">
                                    <li><a href=""><img src="/static/img/logouca2.png" alt=""></a></li>
                                    <li><a href=""><img src="/static/img/logoihca.png" alt=""></a></li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </footer>
        <a href="#" class="back-to-top">Back to Top</a>

        <!-- jQuery -->
        <script src="/static/js/jquery.min.js"></script>
        <!-- Bootstrap JavaScript -->
        <script src="/static/bootstrap/js/bootstrap.js"></script>
        <script type="text/javascript">
            var amountScrolled = 300;

            $(window).scroll(function() {
                if ( $(window).scrollTop() > amountScrolled ) {
                    $('a.back-to-top').fadeIn('slow');
                } else {
                    $('a.back-to-top').fadeOut('slow');
                }
            });


            $('a.back-to-top').click(function() {
                $('html, body').animate({
                    scrollTop: 0
                }, 700);
                return false;
            });
            $('#carousel-example').carousel({
                interval: 9000
            });
        </script>
        <script type="text/javascript">
            $(".pagination a:contains('>')").html("<span class='fa fa-arrow-right hide'></span>");
            $(".pagination a:contains('<')").html("<span class='fa fa-arrow-left hide'></span>");
        </script>
        {% block extra_js %}

        {% endblock extra_js %}
    </body>
</html>

templates/index.html
{% extends "base.html" %}

{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load thumbnail %}

{% block extra_js %}
<script type="text/javascript">
 var urlmenu = document.getElementById( 'archivosDrop' );
 urlmenu.onchange = function() {
      window.open( this.options[ this.selectedIndex ].value, '_self');
 };
</script>
{% endblock extra_js %}

{% block contenido %}
 <style type="text/css">
        .barra-superior, .main-manu, .navbar-brand, .idiomas a.activo, .suscripcion a,
        footer,.navbar-toggle .icon-bar,  .navbar-envios{

            background-color: {% for obj in object_list %} {{obj.color.color1}} {%endfor%};
        }
        .idiomas a.activo{
            color: white;
            border-color: {% for obj in object_list %}{{obj.color.color1}}{%endfor%};
        }
        .navbar-toggle{
            border-color: {% for obj in object_list %}{{obj.color.color1}}{%endfor%};
        }
        .revista-actual span, .pais,.pais span,
        .articulos p span a, .articulo-detalle h1, .articulo-detalle h2, .articulo-detalle h3,
        .articulo-detalle h4, .articulo-detalle h5, .articulo-detalle h6, a.link-titulo:hover,
        a.link-titulo:focus {
            color:{% for obj in object_list %} {{obj.color.color1}}{%endfor%};
        }
        hr{
            border-color: {% for obj in object_list %}{{obj.color.color2}}{%endfor%};

        }
        .revista-actual{
            border-bottom: 1px solid {% for obj in object_list %}{{obj.color.color1}}{%endfor%};
        }
        .sidebar, .sm-menu{
            background-color: {% for obj in object_list %}{{obj.color.color2}}{%endfor%};
        }
        .autor-articulo a:hover{
            color:{% for obj in object_list %} {{obj.color.color1}}{%endfor%};
        }

    </style>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
            <div class="revista-actual">
                <span class="fa fa-calendar"> {% for obj in object_list %}{{ obj.get_mes_display }} {{obj.ano}} {% endfor %}</span>
                <span class="fa fa-file-o"> {% trans "Número" %} {% for obj in object_list %} {{obj.numero}} {% endfor %}</span>
            </div>
            <div class="articulos">
                {% for revista in object_list %}
                    {% for obj in revista.articulos_set.all %}
                    <div class="item">
                        <h6 class="pais">
                            {% if LANGUAGE_CODE == 'es' %}
                                {{obj.idzona}}
                            {% else %}
                                {{obj.idzona.zona_en}}
                            {% endif %}

                            
                            <span>

                                {% if LANGUAGE_CODE == 'es' %}
                                    
                                {% else %}
                                    {% if obj.opinion %}
                                        - {{obj.get_opinion_display}}
                                    {% endif %}
                                   
                                {% endif %}
                            </span>
                        </h6>
                        
                        
                        <h5 class="articulo-titulo"><a href="{% url 'articulo-detalle' obj.id %}">{{obj}}</a></h5>
                        <p>
                        	{{obj.texto|truncatewords:22|striptags|safe }}
                        	<span><a href="{% url 'articulo-detalle' obj.id %}"><span class="fa fa-arrow-right"></span></a><span>
                        </p>
                    </div>
                    <hr>
                    {% endfor %}
                {% endfor %}


                {% if is_paginated %}
                    <div class="paginado">
                        {% if page_obj.has_previous %}
                            <a class="right" href="/?page={{ page_obj.previous_page_number }}">
                                {% trans "Siguiente"%} <span class="fa fa-arrow-right"></span>
                            </a>
                        {% endif %}

                        {% if page_obj.has_next %}
                         <a class="left" href="/?page={{ page_obj.next_page_number }}">
                            <span class="fa fa-arrow-left"></span>{% trans "Anterior"%} 
                        </a>
                        {% endif %}

                        
                    </div>
                {% endif %}

            </div>
        </div>
        {% include "sidebar.html" %}
    </div>
</div>
{% endblock contenido %}